### PR TITLE
make esbuild a dev dependency

### PR DESCRIPTION
**Pull request by arty-name**

### CODE REVIEW

**Comment by TimDaub** [comment]
thank u

**Comment by arty-name** [comment]
Well, the options for labels were not optional, so I haven’t looked deeper and switched to [`echarts`](https://echarts.apache.org/). It looks quite mature, very flexible, and well-supported by the Apache Foundation.

**Comment by arty-name** [comment]
I very much appreciate your helpfulness anyway!

**Comment by arty-name** [comment]
Probably not. I’ve spent too much time already on that seemingly straightforward task, and would not like to invest more in it. 

I could share a tip though: if you put `<title>name: value</title>` inside most of the SVG elements, they’d get a standard tooltip in the browser.

**Pull request merged**
